name: Intégration Continue Vault + Terraform + GitHub Actions CI sécurisée
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  vault:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vault

    services:
      vault:
        image: vault:1.13.3
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_DEV_LISTEN_ADDRESS: """



  terraform:
    needs: vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/preview'
        run: terraform apply -auto-approve




