name: Intégration Continue Vault + Terraform + GitHub Actions CI sécurisée
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  # vault:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./vault

  #   services:
  #     vault:
  #       image: vault:1.13.3
  #       ports:
  #         - 8200:8200
  #       env:
  #         VAULT_DEV_ROOT_TOKEN_ID: root
  #         VAULT_DEV_LISTEN_ADDRESS: "http://localhost:8200"


  terraform:
    needs: vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/preview'
        run: terraform apply -auto-approve

  tflint:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run TFLint
        run: tflint --init && tflint


  checkov:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Checkov
        uses: bridgecrewio/checkov-action@v9.0.0

      - name: Run Checkov
        run: checkov -d . --quiet --compact --output json --output-file-path checkov_report.json

  # Semgrep:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Semgrep
  #       uses: returntocorp/semgrep-action@v1

  #     - name: Run Semgrep
  #       run: semgrep --config=auto
  
  # trivy:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Trivy
  #       uses: aquasecurity/trivy-action@v0.7.0

  #     - name: Run Trivy
  #       run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
  
  # zapbaseline:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up OWASP ZAP Baseline Scan
  #       uses: zaproxy/action-baseline@v0.6.0

  #     - name: Run OWASP ZAP Baseline Scan
  #       run: zap-baseline.py -t http://localhost:8080 -g gen.conf -r zap_report.html
  
  # cosign:
  #   needs: terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Cosign
  #       uses: sigstore/cosign-action@v1.3.0

  #     - name: Sign artifacts with Cosign
  #       run: cosign sign --key cosign.key <artifact>




